export const items = [
  {
    name: "Jane Smith",
    price: 200,
    description: "A detailed description of the item.",
    image: "https://example.com/image2.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Alex Johnson",
    price: 150,
    description: "Another example description.",
    image: "https://example.com/image3.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Emily Brown",
    price: 300,
    description: "A wonderful product description.",
    image: "https://example.com/image4.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Michael Davis",
    price: 250,
    description: "This product is amazing.",
    image: "https://example.com/image5.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Sarah Wilson",
    price: 350,
    description: "Top-quality product description.",
    image: "https://example.com/image6.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Chris Taylor",
    price: 400,
    description: "Best item in the market.",
    image: "https://example.com/image7.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Laura Moore",
    price: 180,
    description: "Affordable and reliable.",
    image: "https://example.com/image8.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "David Anderson",
    price: 220,
    description: "High-quality and durable.",
    image: "https://example.com/image9.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Sophia Thomas",
    price: 120,
    description: "Excellent product for daily use.",
    image: "https://example.com/image10.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
